export const FONTS = [
  // ── Handwriting / Script ──
  { label: 'Great Vibes',         value: "'Great Vibes', cursive",              category: 'Handwriting' },
  { label: 'Pinyon Script',       value: "'Pinyon Script', cursive",            category: 'Handwriting' },
  { label: 'Allura',              value: "'Allura', cursive",                   category: 'Handwriting' },
  { label: 'Alex Brush',          value: "'Alex Brush', cursive",               category: 'Handwriting' },
  { label: 'Sacramento',          value: "'Sacramento', cursive",               category: 'Handwriting' },
  { label: 'Tangerine',           value: "'Tangerine', cursive",                category: 'Handwriting' },
  { label: 'Dancing Script',      value: "'Dancing Script', cursive",          category: 'Handwriting' },
  { label: 'Satisfy',             value: "'Satisfy', cursive",                  category: 'Handwriting' },
  { label: 'Pacifico',            value: "'Pacifico', cursive",                 category: 'Handwriting' },
  { label: 'Caveat',              value: "'Caveat', cursive",                   category: 'Handwriting' },
  { label: 'Permanent Marker',    value: "'Permanent Marker', cursive",        category: 'Handwriting' },
  { label: 'Shadows Into Light',  value: "'Shadows Into Light', cursive",       category: 'Handwriting' },
  { label: 'Indie Flower',        value: "'Indie Flower', cursive",            category: 'Handwriting' },
  { label: 'Amatic SC',           value: "'Amatic SC', cursive",                category: 'Handwriting' },
  { label: 'Gochi Hand',          value: "'Gochi Hand', cursive",               category: 'Handwriting' },
  { label: 'Homemade Apple',      value: "'Homemade Apple', cursive",          category: 'Handwriting' },
  { label: 'Just Another Hand',   value: "'Just Another Hand', cursive",       category: 'Handwriting' },
  { label: 'Kaushan Script',      value: "'Kaushan Script', cursive",           category: 'Handwriting' },
  { label: 'Yellowtail',          value: "'Yellowtail', cursive",               category: 'Handwriting' },
  { label: 'Lobster',             value: "'Lobster', cursive",                 category: 'Handwriting' },
  { label: 'Lobster Two',         value: "'Lobster Two', cursive",              category: 'Handwriting' },
  { label: 'Parisienne',          value: "'Parisienne', cursive",               category: 'Handwriting' },
  { label: 'Cookie',              value: "'Cookie', cursive",                  category: 'Handwriting' },
  { label: 'Marck Script',       value: "'Marck Script', cursive",             category: 'Handwriting' },
  { label: 'Mr Dafoe',            value: "'Mr Dafoe', cursive",                 category: 'Handwriting' },
  { label: 'Nanum Pen Script',    value: "'Nanum Pen Script', cursive",        category: 'Handwriting' },
  { label: 'Norican',             value: "'Norican', cursive",                  category: 'Handwriting' },
  { label: 'Rochester',           value: "'Rochester', cursive",               category: 'Handwriting' },
  { label: 'Rock Salt',           value: "'Rock Salt', cursive",               category: 'Handwriting' },
  { label: 'Sedgwick Ave',        value: "'Sedgwick Ave', cursive",             category: 'Handwriting' },
  { label: 'Sue Ellen Francisco', value: "'Sue Ellen Francisco', cursive",     category: 'Handwriting' },
  { label: 'Italianno',           value: "'Italianno', cursive",               category: 'Handwriting' },
  { label: 'Petit Formal Script', value: "'Petit Formal Script', cursive",     category: 'Handwriting' },
  { label: 'Mr De Haviland',      value: "'Mr De Haviland', cursive",           category: 'Handwriting' },
  { label: 'Mrs Saint Delafield', value: "'Mrs Saint Delafield', cursive",     category: 'Handwriting' },
  { label: 'Clicker Script',      value: "'Clicker Script', cursive",          category: 'Handwriting' },
  { label: 'Engagement',          value: "'Engagement', cursive",              category: 'Handwriting' },
  { label: 'Tillana',             value: "'Tillana', cursive",                  category: 'Handwriting' },
  { label: 'Bad Script',          value: "'Bad Script', cursive",              category: 'Handwriting' },

  // ── Elegant Serif ──
  { label: 'Cinzel',              value: "'Cinzel', serif",                     category: 'Elegant Serif' },
  { label: 'Cinzel Decorative',   value: "'Cinzel Decorative', serif",          category: 'Elegant Serif' },
  { label: 'Cormorant Garamond',  value: "'Cormorant Garamond', serif",         category: 'Elegant Serif' },
  { label: 'Cormorant',           value: "'Cormorant', serif",                  category: 'Elegant Serif' },
  { label: 'Playfair Display',    value: "'Playfair Display', serif",           category: 'Elegant Serif' },
  { label: 'EB Garamond',         value: "'EB Garamond', serif",                category: 'Elegant Serif' },
  { label: 'Crimson Text',        value: "'Crimson Text', serif",               category: 'Elegant Serif' },
  { label: 'Crimson Pro',         value: "'Crimson Pro', serif",                category: 'Elegant Serif' },
  { label: 'Libre Baskerville',   value: "'Libre Baskerville', serif",          category: 'Elegant Serif' },
  { label: 'Cardo',               value: "'Cardo', serif",                      category: 'Elegant Serif' },
  { label: 'Lora',                value: "'Lora', serif",                      category: 'Elegant Serif' },
  { label: 'Merriweather',        value: "'Merriweather', serif",               category: 'Elegant Serif' },
  { label: 'Source Serif Pro',    value: "'Source Serif Pro', serif",           category: 'Elegant Serif' },
  { label: 'Source Serif 4',      value: "'Source Serif 4', serif",              category: 'Elegant Serif' },
  { label: 'Spectral',            value: "'Spectral', serif",                   category: 'Elegant Serif' },
  { label: 'Prata',               value: "'Prata', serif",                      category: 'Elegant Serif' },
  { label: 'Quattrocento',        value: "'Quattrocento', serif",                category: 'Elegant Serif' },
  { label: 'Old Standard TT',     value: "'Old Standard TT', serif",            category: 'Elegant Serif' },
  { label: 'Frank Ruhl Libre',    value: "'Frank Ruhl Libre', serif",           category: 'Elegant Serif' },
  { label: 'Gelasio',             value: "'Gelasio', serif",                    category: 'Elegant Serif' },
  { label: 'Judson',              value: "'Judson', serif",                    category: 'Elegant Serif' },
  { label: 'Zilla Slab',          value: "'Zilla Slab', serif",                 category: 'Elegant Serif' },
  { label: 'Roboto Slab',         value: "'Roboto Slab', serif",                category: 'Elegant Serif' },
  { label: 'Trispace',            value: "'Trispace', serif",                   category: 'Elegant Serif' },

  // ── Classic ──
  { label: 'Georgia',             value: 'Georgia, serif',                      category: 'Classic' },
  { label: 'Palatino',            value: "'Palatino Linotype', serif",          category: 'Classic' },
  { label: 'Times New Roman',     value: "'Times New Roman', serif",            category: 'Classic' },
  { label: 'Cambria',             value: 'Cambria, serif',                     category: 'Classic' },
  { label: 'Garamond',            value: 'Garamond, serif',                    category: 'Classic' },
  { label: 'Book Antiqua',        value: "'Book Antiqua', serif",                category: 'Classic' },
  { label: 'Baskerville',         value: 'Baskerville, serif',                 category: 'Classic' },
  { label: 'Hoefler Text',        value: "'Hoefler Text', serif",                category: 'Classic' },
  { label: 'Optima',              value: 'Optima, serif',                       category: 'Classic' },
  { label: 'Big Caslon',          value: "'Big Caslon', serif",                 category: 'Classic' },
  { label: 'Didot',               value: 'Didot, serif',                       category: 'Classic' },
  { label: 'Bodoni MT',           value: "'Bodoni MT', serif",                  category: 'Classic' },

  // ── Sans-serif ──
  { label: 'Inter',               value: "'Inter', sans-serif",                category: 'Sans-serif' },
  { label: 'Raleway',             value: "'Raleway', sans-serif",               category: 'Sans-serif' },
  { label: 'Lato',                value: "'Lato', sans-serif",                  category: 'Sans-serif' },
  { label: 'Roboto',              value: "'Roboto', sans-serif",                category: 'Sans-serif' },
  { label: 'Open Sans',           value: "'Open Sans', sans-serif",             category: 'Sans-serif' },
  { label: 'Montserrat',          value: "'Montserrat', sans-serif",             category: 'Sans-serif' },
  { label: 'Poppins',             value: "'Poppins', sans-serif",               category: 'Sans-serif' },
  { label: 'Nunito',              value: "'Nunito', sans-serif",                 category: 'Sans-serif' },
  { label: 'Work Sans',           value: "'Work Sans', sans-serif",             category: 'Sans-serif' },
  { label: 'Mulish',              value: "'Mulish', sans-serif",                category: 'Sans-serif' },
  { label: 'Rubik',               value: "'Rubik', sans-serif",                 category: 'Sans-serif' },
  { label: 'Manrope',             value: "'Manrope', sans-serif",               category: 'Sans-serif' },
  { label: 'Heebo',               value: "'Heebo', sans-serif",                  category: 'Sans-serif' },
  { label: 'Karla',               value: "'Karla', sans-serif",                  category: 'Sans-serif' },
  { label: 'DM Sans',             value: "'DM Sans', sans-serif",               category: 'Sans-serif' },
  { label: 'Outfit',              value: "'Outfit', sans-serif",                category: 'Sans-serif' },
  { label: 'Sora',                value: "'Sora', sans-serif",                  category: 'Sans-serif' },
  { label: 'Space Grotesk',       value: "'Space Grotesk', sans-serif",         category: 'Sans-serif' },
  { label: 'Hind',                value: "'Hind', sans-serif",                  category: 'Sans-serif' },
  { label: 'Jost',                value: "'Jost', sans-serif",                  category: 'Sans-serif' },
  { label: 'Kumbh Sans',          value: "'Kumbh Sans', sans-serif",            category: 'Sans-serif' },
  { label: 'Lexend',              value: "'Lexend', sans-serif",                category: 'Sans-serif' },
  { label: 'Plus Jakarta Sans',   value: "'Plus Jakarta Sans', sans-serif",    category: 'Sans-serif' },
  { label: 'Figtree',             value: "'Figtree', sans-serif",               category: 'Sans-serif' },
  { label: 'Onest',               value: "'Onest', sans-serif",                 category: 'Sans-serif' },
  { label: 'Hanken Grotesk',      value: "'Hanken Grotesk', sans-serif",        category: 'Sans-serif' },
  { label: 'Albert Sans',         value: "'Albert Sans', sans-serif",          category: 'Sans-serif' },
  { label: 'Bricolage Grotesque', value: "'Bricolage Grotesque', sans-serif",   category: 'Sans-serif' },
  { label: 'Arial',               value: 'Arial, sans-serif',                   category: 'Sans-serif' },
  { label: 'Verdana',             value: 'Verdana, sans-serif',                category: 'Sans-serif' },
  { label: 'Helvetica',           value: 'Helvetica, sans-serif',               category: 'Sans-serif' },
  { label: 'Tahoma',              value: 'Tahoma, sans-serif',                 category: 'Sans-serif' },
  { label: 'Trebuchet MS',        value: "'Trebuchet MS', sans-serif",          category: 'Sans-serif' },
  { label: 'Calibri',             value: 'Calibri, sans-serif',                category: 'Sans-serif' },
  { label: 'Segoe UI',            value: "'Segoe UI', sans-serif",              category: 'Sans-serif' },

  // ── Display ──
  { label: 'Anton',               value: "'Anton', sans-serif",                category: 'Display' },
  { label: 'Bebas Neue',          value: "'Bebas Neue', sans-serif",            category: 'Display' },
  { label: 'Oswald',              value: "'Oswald', sans-serif",                category: 'Display' },
  { label: 'Archivo Black',       value: "'Archivo Black', sans-serif",        category: 'Display' },
  { label: 'Righteous',           value: "'Righteous', sans-serif",             category: 'Display' },
  { label: 'Fredoka',             value: "'Fredoka', sans-serif",               category: 'Display' },
  { label: 'Bungee',              value: "'Bungee', sans-serif",                 category: 'Display' },
  { label: 'Concert One',         value: "'Concert One', cursive",              category: 'Display' },
  { label: 'Russo One',           value: "'Russo One', sans-serif",             category: 'Display' },
  { label: 'Teko',                value: "'Teko', sans-serif",                  category: 'Display' },
  { label: 'Barlow Condensed',    value: "'Barlow Condensed', sans-serif",      category: 'Display' },
  { label: 'Saira Condensed',     value: "'Saira Condensed', sans-serif",       category: 'Display' },
  { label: 'Yeseva One',          value: "'Yeseva One', serif",                 category: 'Display' },
  { label: 'Abril Fatface',       value: "'Abril Fatface', serif",              category: 'Display' },
  { label: 'Playfair Display SC', value: "'Playfair Display SC', serif",        category: 'Display' },
  { label: 'Cinzel Decorative Blk', value: "'Cinzel Decorative', serif",        category: 'Display' },

  // ── Monospace ──
  { label: 'Courier New',         value: "'Courier New', monospace",            category: 'Monospace' },
  { label: 'JetBrains Mono',      value: "'JetBrains Mono', monospace",        category: 'Monospace' },
  { label: 'Fira Code',           value: "'Fira Code', monospace",              category: 'Monospace' },
  { label: 'Source Code Pro',     value: "'Source Code Pro', monospace",       category: 'Monospace' },
  { label: 'IBM Plex Mono',       value: "'IBM Plex Mono', monospace",          category: 'Monospace' },
  { label: 'Roboto Mono',         value: "'Roboto Mono', monospace",           category: 'Monospace' },
  { label: 'Ubuntu Mono',         value: "'Ubuntu Mono', monospace",           category: 'Monospace' },
  { label: 'Space Mono',          value: "'Space Mono', monospace",            category: 'Monospace' },
  { label: 'Inconsolata',         value: "'Inconsolata', monospace",             category: 'Monospace' },
  { label: 'Monaco',              value: 'Monaco, monospace',                   category: 'Monospace' },
  { label: 'Consolas',            value: 'Consolas, monospace',                 category: 'Monospace' },
  { label: 'Menlo',               value: 'Menlo, monospace',                    category: 'Monospace' },
];
